// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActionsLinkController from "./actions_link_controller"
application.register("actions-link", ActionsLinkController)

import FlashAlertsController from "./flash_alerts_controller"
application.register("flash-alerts", FlashAlertsController)

import ScrollOpacityController from "./scroll_opacity_controller"
application.register("scroll-opacity", ScrollOpacityController)

import SystemThemeController from "./system_theme_controller"
application.register("system-theme", SystemThemeController)
